/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MenuItems,
  SubMenuItems,
} from './components/q-menu/model/menu-item.model';

export namespace Components {
  interface QMenu {
    'closeMenuIcon': any;
    'imgPath': string;
    'menuItems': MenuItems[];
    'openMenuIcon': any;
  }
  interface QSideSubMenu {
    'subMenu': SubMenuItems[];
  }
  interface QSubMenu {
    'subMenu': SubMenuItems[];
  }
}

declare global {


  interface HTMLQMenuElement extends Components.QMenu, HTMLStencilElement {}
  var HTMLQMenuElement: {
    prototype: HTMLQMenuElement;
    new (): HTMLQMenuElement;
  };

  interface HTMLQSideSubMenuElement extends Components.QSideSubMenu, HTMLStencilElement {}
  var HTMLQSideSubMenuElement: {
    prototype: HTMLQSideSubMenuElement;
    new (): HTMLQSideSubMenuElement;
  };

  interface HTMLQSubMenuElement extends Components.QSubMenu, HTMLStencilElement {}
  var HTMLQSubMenuElement: {
    prototype: HTMLQSubMenuElement;
    new (): HTMLQSubMenuElement;
  };
  interface HTMLElementTagNameMap {
    'q-menu': HTMLQMenuElement;
    'q-side-sub-menu': HTMLQSideSubMenuElement;
    'q-sub-menu': HTMLQSubMenuElement;
  }
}

declare namespace LocalJSX {
  interface QMenu extends JSXBase.HTMLAttributes<HTMLQMenuElement> {
    'closeMenuIcon'?: any;
    'imgPath'?: string;
    'menuItems'?: MenuItems[];
    'openMenuIcon'?: any;
  }
  interface QSideSubMenu extends JSXBase.HTMLAttributes<HTMLQSideSubMenuElement> {
    'onRouteClicked'?: (event: CustomEvent<any>) => void;
    'subMenu'?: SubMenuItems[];
  }
  interface QSubMenu extends JSXBase.HTMLAttributes<HTMLQSubMenuElement> {
    'onRouteClicked'?: (event: CustomEvent<any>) => void;
    'subMenu'?: SubMenuItems[];
  }

  interface IntrinsicElements {
    'q-menu': QMenu;
    'q-side-sub-menu': QSideSubMenu;
    'q-sub-menu': QSubMenu;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


